---
- name: Install Repo Prereq
  package: name={{ repo_packages }} state=present update_cache=true
  
- name: Install MySQL Prereq
  package: name={{ pre_packages }} state=present

- name: Add repo for CentOS 7
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Install MySQL
  package: name={{ mysql_packages }} state=present

- name: Start MySQL Service
  service:
    name: '{{ mysql_service }}'
    state: started
    enabled: yes

- name: Remove Database
  mysql_db : name={{ db_name }} state=absent

- name: Create Database
  mysql_db : name={{ db_name }} state=present

- name: Create Database User
  mysql_user:
    name: '{{ mysql_user_name }}'
    password: '{{ mysql_user_password }}'
    priv: '{{ db_name }}.*:ALL'
    state: present
