---
- name: Install MySQL Prereq
  package: name={{ packages }} state=present

- name: DE
  debug:
    msg: name={{ mysql_packages }} ad ={{ ansible_distribution }} adm= {{ ansible_distribution_major_version }}

- name: Install MySQL
  package: name={{ mysql_packages }} state=present

- name: Start MySQL Service
  service:
    name: '{{ mysql_service }}'
    state: started
    enabled: yes

- name: Create Database
  mysql_db : name={{ db_name }} state=present

- name: Create Database User
  mysql_user:
    name: '{{ mysql_user_name }}'
    password: '{{ mysql_user_password }}'
    priv: '*.*:ALL'
    state: present
    host: '%'
