---
- name: Install Repo Prereq
  package: name={{ repo_packages }} state=present update_cache=yes
  
- name: Install MySQL Prereq
  package: name={{ pre_packages }} state=present

- name: Add repo for CentOS 7
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Install MySQL
  package: name={{ mysql_packages }} state=present

- name: Start MySQL Service
  service:
    name: '{{ mysql_service }}'
    state: started
    enabled: yes

- name: Set password for root user
  mysql_user:
    name: "root"
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "9"

- name: Save root password in .my.cnf
  template:
    src: root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "9"

- name: Remove Database
  mysql_db : name={{ db_name }} state=absent

- name: Create Database
  mysql_db : name={{ db_name }} state=present

- name: Create Database User
  mysql_user:
    name: '{{ mysql_user_name }}'
    password: '{{ mysql_user_password }}'
    priv: '{{ db_name }}.*:ALL'
    state: present
